language: php

php: 7.2

before_install:
- composer global require hirak/prestissimo

install:
- composer install

before_script:
- phpenv config-rm xdebug.ini

script:
- composer run lint
- composer run build
- bin/sync

notifications:
 email:
 - team@redaxscript.com
