language: php

php:
- 7.1

before_install:
- composer global require hirak/prestissimo

install:
- composer self-update
- composer install

script:
- vendor/bin/phpdoc --no-ansi
- bin/sync

notifications:
 email:
 - team@redaxscript.com
 irc:
 - chat.freenode.net#redaxscript
 webhooks:
 - https://webhooks.gitter.im/e/ff9acda2e5faf42e3182
